# Generated by Django 4.2.1 on 2023-06-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_profile', '0002_alter_petsimage_owner_alter_petsprofile_tinder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsimage',
            old_name='owner',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='petsprofile',
            old_name='tinder_user',
            new_name='users',
        ),
    ]
