# Generated by Django 4.2.1 on 2023-06-08 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets_profile', '0003_rename_owner_petsimage_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsprofile',
            name='connected_profiles',
            field=models.ManyToManyField(blank=True, to='pets_profile.petsprofile'),
        ),
        migrations.AddField(
            model_name='petsprofile',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petsprofile',
            name='users',
            field=models.ForeignKey(db_column='users_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
