# Generated by Django 4.2.1 on 2023-06-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets_profile', '0006_alter_petsprofile_connected_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsprofile',
            name='connected_profiles',
        ),
        migrations.AddField(
            model_name='petsprofile',
            name='connected_profiles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets_profile.petsprofile'),
        ),
    ]
