# Generated by Django 4.2.1 on 2023-06-08 16:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets_profile', '0007_remove_petsprofile_connected_profiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsprofile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
