# Generated by Django 4.2.1 on 2023-06-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_profile', '0008_alter_petsprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsprofile',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
