# Generated by Django 4.2.1 on 2023-06-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets_profile', '0009_petsprofile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsprofile',
            name='connected_profiles',
        ),
        migrations.AddField(
            model_name='petsprofile',
            name='connected_profiles',
            field=models.ManyToManyField(blank=True, to='pets_profile.petsprofile'),
        ),
    ]
